CREATE DATABASE products;

CREATE TABLE products (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  slogan VARCHAR(1000) NOT NULL,
  description VARCHAR (1000) NOT NULL,
  category VARCHAR(100) NOT NULL
);